# Generated by Django 5.2.5 on 2025-09-12 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(verbose_name='Price')),
                ('descriptions', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item_views', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('men sportwear', 'Men Sportwear'), ('women sportwear', 'Women Sportwear'), ('kids sportwear', 'Kids Sportwear'), ('accessories', 'Accessories'), ('equipment', 'Sports Equipment'), ('bags', 'Bags & Backpacks'), ('outerwear', 'Jackets & Hoodies')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
