# Generated by Django 5.2.6 on 2025-10-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('men_sportwear', 'Men Sportwear'), ('women_sportwear', 'Women Sportwear'), ('kids_sportwear', 'Kids Sportwear'), ('accessories', 'Accessories'), ('equipment', 'Sports Equipment'), ('bags', 'Bags & Backpacks'), ('outerwear', 'Jackets & Hoodies')], max_length=50),
        ),
    ]
